### ISSUE TITLE
04 Initial Configuration Scans on Windows

### ISSUE THREAD

**Issue by burtlo** [chef-training/chef-compliance-installation-configuration-operation#5]
On Slide 4-9 you have the learner prefix the system with 'Windows'.

<img width="782" alt="2016-02-08_14-59-55" src="https://cloud.githubusercontent.com/assets/244426/12898905/a12d4cc4-ce74-11e5-8551-56fa7583cc80.png">

I assume it is because the Dashboard view in a previous version did not report the correct OS for Windows. That appears to be fixed in the current dashboard.

<img width="1137" alt="2016-02-08_15-02-04" src="https://cloud.githubusercontent.com/assets/244426/12898995/edd2bcda-ce74-11e5-9a78-128bef797010.png">

I don't know that prefixing the system is necessary.

**Comment by SteveDelFante** [comment]
I also have them type `Windows` because until you actually scan a node, the OS field will be blank. So this differentiates the node clearly for students.Yes, some could deduce it, but I wanted it crystal clear and also to demo the ability to modify the name.

**Comment by burtlo** [comment]
Makes sense.
